FileVersion = 1

[Project]
Name = "gravity-beef"
DefaultNamespace = "gravity"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\gravityd.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\gravity.lib"]
