FileVersion = 1

[Project]
Name = "gravity-beef"
DefaultNamespace = "gravity"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\gravityapi_s_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\gravityapi_s.lib"]
