FileVersion = 1

[Project]
Name = "gravity-beef"
TargetType = "BeefLib"
StartupObject = "gravity_beef.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\gravity.lib"]
